#!/usr/bin/env python3
import argparse
import subprocess
import uuid

from datetime import datetime

from sylva_algorithm_runner import YamlConfiguration
from sylva_algorithm_runner.repositories import DatabaseRepository

configuration = YamlConfiguration("/etc/sylva-algorithm-runner/config.yaml")
database_repository = DatabaseRepository(configuration.get("database"))

parser = argparse.ArgumentParser(description="""Finds next algorithm run to execute and executes it.""")
parser.add_argument("--overrideEnabled", help="runs even if it is disabled in configuration file", action="store_true", default=False)

args = parser.parse_args()

process_id = str(uuid.uuid4())
print("{0} - {1} - START - Getting next algorithm to run.".format(datetime.now().isoformat(), process_id))

if (configuration.get("runner")["run-autostart-enabled"] == True or args.overrideEnabled == True):
    max_runs_in_parallel = configuration.get("runner")["parallel"]

    ids_to_run = database_repository.find_next_to_run_id(max_runs_in_parallel)

    processes = []
    for id_to_run in ids_to_run:
        print("{0} - {1} - INFO - Starting {2}.".format(datetime.now().isoformat(), process_id, id_to_run))
        process = subprocess.Popen(["sylva-algorithm-run", id_to_run])
        processes.append(process)

    for process in processes:
        process.wait()

    print("{0} - {1} - END - Process finished.".format(datetime.now().isoformat(), process_id))

else:
     print("{0} - {1} - END - Process skipped as run-autostart is set to False.".format(datetime.now().isoformat(), process_id))