github:
  repository: bioaerosol/sylva-algorithm-runner-configs
  token: changeit
database:
  host: localhost
  port: 27017
  user: sylva
  password: changeit
  database: algorithm
runner:
  upgrade-run-orders-enabled: false
  run-autostart-enabled: false
  path: changeit
  workspace: /mnt/changeit
  output: changeit
dataportal:
  workspace: https://data.sylva.bioaerosol.eu/api/workspace
  token: changeit 