github:
  repository: bioaerosol/sylva-algorithm-runner-configs
  token: changeit
database:
  host: localhost
  port: 27017
  user: sylva
  password: changeit
runner:
  path: changeit
  workspace: /mnt/changeit
  output: changeit
dataportal:
  workspace: https://data.sylva.bioaerosol.eu/api/workspace
  token: changeit 